package vista;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;


public class login extends javax.swing.JFrame {

  
    public login() {
        initComponents();
         this.setLocationRelativeTo(null);
        this.setResizable(false);
        ImageIcon fondo = new ImageIcon(getClass().getResource("/imagenes/interamericanoooooo.jpg"));
     ImageIcon fondoo = new ImageIcon(fondo.getImage().getScaledInstance(LabelLogo.getWidth(), LabelLogo.getHeight(), Image.SCALE_DEFAULT));
    LabelLogo.setIcon(fondoo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ingresar = new javax.swing.JButton();
        txt_contraseña = new javax.swing.JPasswordField();
        txt_usuario = new javax.swing.JTextField();
        usuario = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        jTexfieldPH_FielTex1 = new LIB.JTexfieldPH_FielTex();
        panel_central = new LIB.JPanelRound();
        bienvenido = new javax.swing.JLabel();
        text_usuario = new LIB.JTexfieldPH_FielTex();
        susuarios = new javax.swing.JLabel();
        txt_password = new LIB.JTexfieldPH_Password();
        candado = new javax.swing.JLabel();
        boton_ingresar = new javax.swing.JButton();
        LabelLogo = new javax.swing.JLabel();

        btn_ingresar.setText("Aceptar");

        usuario.setText("usuario");

        contraseña.setText("contraseña");

        jTexfieldPH_FielTex1.setText("jTexfieldPH_FielTex1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_central.setBackground(new java.awt.Color(0, 120, 215));
        panel_central.setColorPrimario(new java.awt.Color(0, 153, 255));
        panel_central.setColorSecundario(new java.awt.Color(73, 162, 80));

        bienvenido.setFont(new java.awt.Font("Rockwell", 3, 48)); // NOI18N
        bienvenido.setForeground(new java.awt.Color(255, 255, 255));
        bienvenido.setText("Bienvenido");
        bienvenido.setFocusable(false);
        bienvenido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        text_usuario.setBorder(null);

        susuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N

        txt_password.setBorder(null);
        txt_password.setPlaceholder("Contraseña:");
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });

        candado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/candado.png"))); // NOI18N

        boton_ingresar.setBackground(new java.awt.Color(0, 120, 215));
        boton_ingresar.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        boton_ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iniciar-la-sesion.png"))); // NOI18N
        boton_ingresar.setText("ingresar");
        boton_ingresar.setBorder(null);
        boton_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_ingresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_ingresar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        boton_ingresar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boton_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ingresarActionPerformed(evt);
            }
        });

        LabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interamericanoooooo.jpg"))); // NOI18N

        javax.swing.GroupLayout panel_centralLayout = new javax.swing.GroupLayout(panel_central);
        panel_central.setLayout(panel_centralLayout);
        panel_centralLayout.setHorizontalGroup(
            panel_centralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_centralLayout.createSequentialGroup()
                .addGroup(panel_centralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_centralLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(candado)
                        .addGap(18, 18, 18)
                        .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_centralLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(panel_centralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_centralLayout.createSequentialGroup()
                                .addComponent(bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(LabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, Short.MAX_VALUE))
                            .addGroup(panel_centralLayout.createSequentialGroup()
                                .addComponent(susuarios)
                                .addGap(18, 18, 18)
                                .addComponent(text_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel_centralLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(boton_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        panel_centralLayout.setVerticalGroup(
            panel_centralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_centralLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panel_centralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panel_centralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(susuarios))
                .addGap(93, 93, 93)
                .addGroup(panel_centralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(candado)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(boton_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_central, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel_central, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ingresarActionPerformed
        // TODO add your handling p.setVisible(true);
        
        ///
        Menu_opciones menu = new Menu_opciones();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_boton_ingresarActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed

    }//GEN-LAST:event_txt_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }
    
    

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JButton boton_ingresar;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JLabel candado;
    private javax.swing.JLabel contraseña;
    private LIB.JTexfieldPH_FielTex jTexfieldPH_FielTex1;
    private LIB.JPanelRound panel_central;
    private javax.swing.JLabel susuarios;
    private LIB.JTexfieldPH_FielTex text_usuario;
    private javax.swing.JPasswordField txt_contraseña;
    private LIB.JTexfieldPH_Password txt_password;
    private javax.swing.JTextField txt_usuario;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
