/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import Objetos.Conexion;
import Objetos.Grados;
import Objetos.Secciones;
import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;


/**
 *
 * @author asd
 */
public class Materia extends javax.swing.JFrame {

    /**
     * Creates new form Materia
     */
    public Materia() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        Grados Cg = new Grados();
           DefaultComboBoxModel modeloGrado = new DefaultComboBoxModel(Cg.mostrarGrados());
           cbx_grado.setModel(modeloGrado);
           Secciones Sc = new Secciones();
           DefaultComboBoxModel modeloSeccion = new DefaultComboBoxModel(Sc.mostrarSecciones());
           cbx_Seccion.setModel(modeloSeccion);
    }
    
    public void cargar_materias(JComboBox cbx_grado){

        
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_fondo = new LIB.JPanelRound();
        cbx_Seccion = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_NombreMateria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_Agregar = new javax.swing.JButton();
        cbx_grado = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btn_Regresar = new javax.swing.JButton();
        txt_año = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_fondo.setColorPrimario(new java.awt.Color(0, 120, 215));
        panel_fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_fondo.add(cbx_Seccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 50, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Grado");
        panel_fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 60, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Seccion");
        panel_fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 70, 30));

        txt_NombreMateria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panel_fondo.add(txt_NombreMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 210, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Materia");
        panel_fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Nombre de la materia");
        panel_fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 190, 30));

        btn_Agregar.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btn_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plus.png"))); // NOI18N
        btn_Agregar.setText("Agregar");
        btn_Agregar.setBorder(null);
        btn_Agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Agregar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_Agregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });
        panel_fondo.add(btn_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 90, 60));

        panel_fondo.add(cbx_grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 220, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Año");
        panel_fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, 20));

        btn_Regresar.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btn_Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logout.png"))); // NOI18N
        btn_Regresar.setText("Regresar");
        btn_Regresar.setBorder(null);
        btn_Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Regresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Regresar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_Regresar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegresarActionPerformed(evt);
            }
        });
        panel_fondo.add(btn_Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 70, 60));
        panel_fondo.add(txt_año, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 70, -1));

        getContentPane().add(panel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegresarActionPerformed
        // TODO add your handling code here:
         Opciones_Materia Op_M = new Opciones_Materia();
        Op_M.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_RegresarActionPerformed

    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
        // TODO add your handling code here:
        int cod_materia=0;
         try{
 com.mysql.jdbc.PreparedStatement pr = null;
    ResultSet rs = null;
   Conexion conn = new Conexion();
   Connection con =  (Connection) conn.getConexion();
        pr = (com.mysql.jdbc.PreparedStatement) con.prepareStatement("INSERT INTO `materia` (Materia) VALUES (?)");
        pr.setString(1,txt_NombreMateria.getText());;

                int res = pr.executeUpdate();
            
            if(res > 0)
            {
                JOptionPane.showMessageDialog(null,"Materia Guardada en la BD");
                try{
            com.mysql.jdbc.PreparedStatement pw = null;
            ResultSet rw = null;   
            pw =(com.mysql.jdbc.PreparedStatement) con.prepareStatement("SELECT * FROM materia where materia='"+txt_NombreMateria.getText()+"'");
           
            rw = pw.executeQuery();

            if(rw.next())
            {
                cod_materia=rw.getInt("Id_Materia");
            }else{
                JOptionPane.showMessageDialog(null,"Error no se pudo encontrar datos ...");

            }

        }catch(Exception e){
            System.err.println("Error en la BD");
            
        }
                
            }else{
                JOptionPane.showMessageDialog(null," Error no se pudo guardar datos ...");
            } 
        con.close();
    }catch(Exception e){
        System.err.println(" Error en la BD");
    }
         
         
         try{
   com.mysql.jdbc.PreparedStatement pr = null;
    ResultSet rs = null;
   Conexion conn = new Conexion();
   Connection con =  (Connection) conn.getConexion();
  
        pr = (com.mysql.jdbc.PreparedStatement) con.prepareStatement("INSERT INTO pensum (año, Id_Grado, Id_Materia) VALUES (?, ?, ?)");
        pr.setString(1,txt_año.getText());
        pr.setInt(2,cbx_grado.getSelectedIndex());
        pr.setInt(3,cod_materia);
        
                int res = pr.executeUpdate();
            
            if(res > 0)
            {
                JOptionPane.showMessageDialog(null,"Materia Guardada en el pensum");
            }else{
                JOptionPane.showMessageDialog(null," Error no se pudo guardar datos ...");
            } 
        con.close();
    }catch(Exception e){
        System.err.println(" Error en la BD");
    }
        
    }//GEN-LAST:event_btn_AgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Materia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Materia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Materia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Materia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Materia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_Regresar;
    private javax.swing.JComboBox<String> cbx_Seccion;
    private javax.swing.JComboBox<String> cbx_grado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private LIB.JPanelRound panel_fondo;
    private javax.swing.JTextField txt_NombreMateria;
    private javax.swing.JTextField txt_año;
    // End of variables declaration//GEN-END:variables
}

