/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Giancarlo
 */
public class Menu_opciones extends javax.swing.JFrame {

    /**
     * Creates new form Menu_opciones
     */
    public Menu_opciones() {
        initComponents();
         this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_secundario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_botones = new javax.swing.JPanel();
        btn_alumno = new javax.swing.JButton();
        Materia = new javax.swing.JButton();
        Notas = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        Profesor = new javax.swing.JButton();
        btn_usuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel_secundario.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Bienvenido");

        panel_botones.setBackground(new java.awt.Color(51, 102, 255));
        panel_botones.setLayout(null);

        btn_alumno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_alumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alumnos.png"))); // NOI18N
        btn_alumno.setText("Nuevo Alumno");
        btn_alumno.setBorder(null);
        btn_alumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_alumno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_alumno.setMaximumSize(new java.awt.Dimension(130, 182));
        btn_alumno.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_alumno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alumnoActionPerformed(evt);
            }
        });
        panel_botones.add(btn_alumno);
        btn_alumno.setBounds(0, 180, 250, 170);

        Materia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Materia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/materia.png"))); // NOI18N
        Materia.setText("Materia");
        Materia.setBorder(null);
        Materia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Materia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Materia.setMaximumSize(new java.awt.Dimension(130, 182));
        Materia.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Materia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MateriaActionPerformed(evt);
            }
        });
        panel_botones.add(Materia);
        Materia.setBounds(250, 180, 250, 170);

        Notas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Notas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/notas.png"))); // NOI18N
        Notas.setText("Notas");
        Notas.setBorder(null);
        Notas.setBorderPainted(false);
        Notas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Notas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Notas.setMaximumSize(new java.awt.Dimension(130, 182));
        Notas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Notas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Notas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotasActionPerformed(evt);
            }
        });
        panel_botones.add(Notas);
        Notas.setBounds(500, 0, 250, 180);

        exit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        exit.setText("exit");
        exit.setBorder(null);
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exit.setMaximumSize(new java.awt.Dimension(130, 182));
        exit.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        exit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        panel_botones.add(exit);
        exit.setBounds(500, 180, 250, 170);

        Profesor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Profesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/profesor.png"))); // NOI18N
        Profesor.setText("Nuevo Profesor");
        Profesor.setBorder(null);
        Profesor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Profesor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Profesor.setMaximumSize(new java.awt.Dimension(130, 182));
        Profesor.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Profesor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Profesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfesorActionPerformed(evt);
            }
        });
        panel_botones.add(Profesor);
        Profesor.setBounds(250, 0, 250, 180);

        btn_usuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        btn_usuario.setText("Reportes ");
        btn_usuario.setBorder(null);
        btn_usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_usuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_usuario.setMaximumSize(new java.awt.Dimension(130, 182));
        btn_usuario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_usuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuarioActionPerformed(evt);
            }
        });
        panel_botones.add(btn_usuario);
        btn_usuario.setBounds(0, 0, 250, 180);

        javax.swing.GroupLayout panel_secundarioLayout = new javax.swing.GroupLayout(panel_secundario);
        panel_secundario.setLayout(panel_secundarioLayout);
        panel_secundarioLayout.setHorizontalGroup(
            panel_secundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_secundarioLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panel_secundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_secundarioLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel1))
                    .addComponent(panel_botones, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_secundarioLayout.setVerticalGroup(
            panel_secundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_secundarioLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(panel_botones, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_secundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_secundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuarioActionPerformed
        // TODO add your handling code here:
        MenuReportes MR = new MenuReportes();
        MR.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_usuarioActionPerformed

    private void btn_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alumnoActionPerformed
        // TODO add your handling code here:
         Nuevo_alumno Alumno = new Nuevo_alumno();
        Alumno.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_alumnoActionPerformed

    private void ProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfesorActionPerformed
        // TODO add your handling code here:
        Profesor profesor = new Profesor();
        profesor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ProfesorActionPerformed

    private void MateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MateriaActionPerformed
        // TODO add your handling code here:
        Opciones_Materia Op_M = new Opciones_Materia();
        Op_M.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MateriaActionPerformed

    private void NotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotasActionPerformed
        // TODO add your handling code here:
       Notas Op_N = new Notas();
        Op_N.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_NotasActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        login  n=new login();
        this.setVisible(false);
        n.setVisible(true);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_opciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Materia;
    private javax.swing.JButton Notas;
    private javax.swing.JButton Profesor;
    private javax.swing.JButton btn_alumno;
    private javax.swing.JButton btn_usuario;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel_botones;
    private javax.swing.JPanel panel_secundario;
    // End of variables declaration//GEN-END:variables
}
