/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Objetos.Conexion;
import Objetos.Grados;
import Objetos.Materias;
import Objetos.MateriasProfesor;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author asd
 */
public class Notas extends javax.swing.JFrame {

    /**
     * Creates new form Notas
     */
    public Notas() {
        initComponents();
         this.setLocationRelativeTo(null);
        this.setResizable(false);
        jPanel1.setVisible(false);/*
                   Grados Cg = new Grados();
           DefaultComboBoxModel modeloGrado = new DefaultComboBoxModel(Cg.mostrarGrados());
           cbx_grado.setModel(modeloGrado);
           */
cbx_materia.setEnabled(false);
cbx_Bimestre.setEnabled(false);
txt_grado.setEnabled(false);
btn_guardar.setEnabled(false);
btnReporte.setEnabled(false);
           
          
    }
 int cod_Alumno, cod_notas, cod_materia, cod_grado, promedio;
 String GradoAlumno;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTransparente1 = new LIB.JPanelTransparente();
        jLabel1 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        btn_Buscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbx_materia = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_bimestre1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_bimestre2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txt_bimestre3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_bimestre4 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_promedio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_año = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbx_Bimestre = new javax.swing.JComboBox<>();
        btn_regresar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        txt_grado = new javax.swing.JTextField();
        btnReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTransparente1.setColorPrimario(new java.awt.Color(51, 102, 255));
        jPanelTransparente1.setColorSecundario(new java.awt.Color(153, 153, 153));
        jPanelTransparente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Materia");
        jPanelTransparente1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, 26));
        jPanelTransparente1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 210, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Nombre Alumno");
        jPanelTransparente1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 26));
        jPanelTransparente1.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 210, 30));

        btn_Buscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_Buscar.setText("Buscar");
        btn_Buscar.setBorder(null);
        btn_Buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Buscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Buscar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_Buscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });
        jPanelTransparente1.add(btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 110, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Bimestre");
        jPanelTransparente1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, 26));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Grado");
        jPanelTransparente1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, 26));

        cbx_materia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_materiaItemStateChanged(evt);
            }
        });
        jPanelTransparente1.add(cbx_materia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 210, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Bimestre 1");

        txt_bimestre1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_bimestre1.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txt_bimestre1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_bimestre1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 110));

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Bimestre 2");

        txt_bimestre2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_bimestre2.setText("0");
        txt_bimestre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bimestre2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txt_bimestre2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_bimestre2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 110));

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Bimestre 3");

        txt_bimestre3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_bimestre3.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txt_bimestre3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_bimestre3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, 110));

        jPanel5.setBackground(new java.awt.Color(51, 102, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Bimestre 4");

        txt_bimestre4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_bimestre4.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txt_bimestre4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_bimestre4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, 110));

        jPanel6.setBackground(new java.awt.Color(51, 102, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Promedio");

        txt_promedio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_promedio.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txt_promedio, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_promedio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, 110));

        jPanelTransparente1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 590, 150));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Apellido Alumno");
        jPanelTransparente1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 26));
        jPanelTransparente1.add(txt_año, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 80, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Año");
        jPanelTransparente1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, 26));

        cbx_Bimestre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbx_Bimestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Bimestre", "Primer Bimestre", "Segundo Bimestre", "Tercer Bimestre", "Final" }));
        cbx_Bimestre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_BimestreItemStateChanged(evt);
            }
        });
        jPanelTransparente1.add(cbx_Bimestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 210, 30));

        btn_regresar.setBackground(new java.awt.Color(97, 97, 97));
        btn_regresar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        btn_regresar.setText("Regresar");
        btn_regresar.setBorder(null);
        btn_regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_regresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_regresar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_regresar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        jPanelTransparente1.add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 120, 120));

        btn_guardar.setBackground(new java.awt.Color(0, 120, 215));
        btn_guardar.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_guardar.setVerifyInputWhenFocusTarget(false);
        btn_guardar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        jPanelTransparente1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 140, 120));
        jPanelTransparente1.add(txt_grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 110, 30));

        btnReporte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReporte.setText("Generar\nReporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanelTransparente1.add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 140, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelTransparente1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTransparente1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed

        try{
              com.mysql.jdbc.PreparedStatement pr = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            Connection con =  (Connection) conn.getConexion();
            com.mysql.jdbc.PreparedStatement pw = null;
            ResultSet rw = null;   
            pw =(com.mysql.jdbc.PreparedStatement) con.prepareStatement("SELECT  *FROM asignacion INNER JOIN alumno ON asignacion.Id_Alumno=alumno.Id_Alumno INNER JOIN grado ON asignacion.Id_Grado= grado.Id_Grado WHERE  alumno.NombreAlumno='"+txt_nombre.getText()+"' AND alumno.ApellidoAlumno= '"+txt_apellido.getText()+"' AND asignacion.AñoAsignacion='"+txt_año.getText()+"'");
           
            rw = pw.executeQuery();

            if(rw.next())
            {
                JOptionPane.showMessageDialog(null,"Usuario Encontrado");
                 cod_Alumno=rw.getInt("Id_Alumno");
                 GradoAlumno=rw.getString("grado");
                 cod_grado=rw.getInt("id_grado");
                txt_grado.setText(GradoAlumno);
                jPanel1.setVisible(true);
                 txt_bimestre1.setEnabled(false);
               txt_bimestre2.setEnabled(false);
               txt_bimestre3.setEnabled(false);
               txt_bimestre4.setEnabled(false);
               txt_promedio.setEnabled(false);
               cbx_materia.setEnabled(true);
               txt_nombre.setEnabled(false);
               txt_apellido.setEnabled(false);
               txt_año.setEnabled(false);
               btn_Buscar.setEnabled(false);
               btnReporte.setEnabled(true);
            MateriasProfesor Mp = new MateriasProfesor();
           DefaultComboBoxModel modeloMateria = new DefaultComboBoxModel(Mp.mostrarMaterias(txt_grado.getText(),txt_año.getText()));
           cbx_materia.setModel(modeloMateria);
            }else{
                JOptionPane.showMessageDialog(null,"Error no se pudo encontrar datos de usuario ...");
                
            }
            con.close();

        }catch(Exception e){
            System.err.println("Error en la BD al buscar datos de usuario");
            
        }  
        
 
        
        
        

    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
        Menu_opciones menu = new Menu_opciones();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_regresarActionPerformed
int a;
    private void cbx_BimestreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_BimestreItemStateChanged
       if (evt.getStateChange()==ItemEvent.SELECTED){
            a=cbx_Bimestre.getSelectedIndex();
            
           if (a==1){
               
               txt_bimestre1.setEnabled(true);
               txt_bimestre2.setEnabled(false);
               txt_bimestre3.setEnabled(false);
               txt_bimestre4.setEnabled(false);
               txt_promedio.setEnabled(false);
               btn_guardar.setEnabled(true);


            }else if(a==2){
               txt_bimestre1.setEnabled(false);
               txt_bimestre2.setEnabled(true);
               txt_bimestre3.setEnabled(false);
               txt_bimestre4.setEnabled(false);
               txt_promedio.setEnabled(false);
               btn_guardar.setEnabled(true);
            }else if(a==3){
               txt_bimestre1.setEnabled(false);
               txt_bimestre2.setEnabled(false);
               txt_bimestre3.setEnabled(true);
               txt_bimestre4.setEnabled(false);
               txt_promedio.setEnabled(false);
               btn_guardar.setEnabled(true);
            }else if(a==4){
               
               txt_bimestre1.setEnabled(false);
               txt_bimestre2.setEnabled(false);
               txt_bimestre3.setEnabled(false);
               txt_bimestre4.setEnabled(true);
               txt_promedio.setEnabled(false);
               btn_guardar.setEnabled(true);

            }
            

        }
    }//GEN-LAST:event_cbx_BimestreItemStateChanged

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
if (a==1){
promedio =0;
promedio = (Integer.parseInt(txt_bimestre1.getText()))/1;
try{
          PreparedStatement ps = null;
            ResultSet rw = null;
            Conexion conn = new Conexion();
            Connection con =  (Connection) conn.getConexion();             
            ps = (PreparedStatement) con.prepareStatement("UPDATE `notas` SET `nota_primer_bimestre` ="+txt_bimestre1.getText()+",`Promedio` ="+promedio+" WHERE notas.`Id_Notas` = "+cod_notas+";");        
        
        //pr.setInt(9,cod_grado);;
            int res = ps.executeUpdate();
            
            if(res > 0)
            {
                JOptionPane.showMessageDialog(null,"Se Actualizo nota del bimestre 1");
                
            }else{
                JOptionPane.showMessageDialog(null,"Error no se pudo modificar nota del bimestre 1 ...");
                
            }  
            con.close();
        }catch(Exception e){
            System.err.println("Error en la BD al actualizar nota del bimestre 1");
            
        }
                                
            }else if(a==2){
                  promedio =0;
   promedio = (Integer.parseInt(txt_bimestre1.getText())+Integer.parseInt(txt_bimestre2.getText()))/2;
          try{
          PreparedStatement ps = null;
            ResultSet rw = null;
            Conexion conn = new Conexion();
            Connection con =  (Connection) conn.getConexion();             
            ps = (PreparedStatement) con.prepareStatement("UPDATE `notas` SET `nota_segundo_bimestre` ="+txt_bimestre2.getText()+",`Promedio` ="+promedio+" WHERE notas.`Id_Notas` = "+cod_notas+";");        
        
        //pr.setInt(9,cod_grado);;
            int res = ps.executeUpdate();
            
            if(res > 0)
            {
                JOptionPane.showMessageDialog(null,"Se Actualizo nota del bimestre 2");
                
            }else{
                JOptionPane.showMessageDialog(null,"Error no se pudo modificar nota del bimestre 2 ...");
                
            }  
            con.close();
        }catch(Exception e){
            System.err.println("Error en la BD al actualizar nota del bimestre 2");
            
        }
      
  }else if(a==3){
        promedio =0;
  promedio = (Integer.parseInt(txt_bimestre1.getText())+Integer.parseInt(txt_bimestre2.getText())+Integer.parseInt(txt_bimestre3.getText()))/3;
      try{
          PreparedStatement ps = null;
            ResultSet rw = null;
            Conexion conn = new Conexion();
            Connection con =  (Connection) conn.getConexion();             
            ps = (PreparedStatement) con.prepareStatement("UPDATE `notas` SET `nota_tercer_bimestre` ="+txt_bimestre3.getText()+",`Promedio` ="+promedio+" WHERE notas.`Id_Notas` = "+cod_notas+";");        
        
        //pr.setInt(9,cod_grado);;
            int res = ps.executeUpdate();
            
            if(res > 0)
            {
                JOptionPane.showMessageDialog(null,"Se Actualizo nota del bimestre 3");
                
            }else{
                JOptionPane.showMessageDialog(null,"Error no se pudo modificar nota del bimestre 3...");
                
            }  
            con.close();
        }catch(Exception e){
            System.err.println("Error en la BD al actualizar nota del bimestre 3");
            
        }
      
  }else if(a==4){
        promedio =0;
   promedio = (Integer.parseInt(txt_bimestre1.getText())+Integer.parseInt(txt_bimestre2.getText())+Integer.parseInt(txt_bimestre3.getText())+Integer.parseInt(txt_bimestre4.getText()))/4;
      try{
          PreparedStatement ps = null;
            ResultSet rw = null;
            Conexion conn = new Conexion();
            Connection con =  (Connection) conn.getConexion();             
            ps = (PreparedStatement) con.prepareStatement("UPDATE `notas` SET `nota_cuarto_bimestre` ="+txt_bimestre4.getText()+",`Promedio` ="+promedio+" WHERE notas.`Id_Notas` = "+cod_notas+";");        
        
        //pr.setInt(9,cod_grado);;
            int res = ps.executeUpdate();
            
            if(res > 0)
            {
                JOptionPane.showMessageDialog(null,"Se Actualizo nota del bimestre 4");
                
            }else{
                JOptionPane.showMessageDialog(null,"Error no se pudo modificar nota del bimestre 4 ...");
                
            }  
            con.close();
        }catch(Exception e){
            System.err.println("Error en la BD al actualizar nota del bimestre 4");
            
        }
      
  }
        txt_promedio.setText(Integer.toString(promedio));
     
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void txt_bimestre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bimestre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bimestre2ActionPerformed

    private void cbx_materiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_materiaItemStateChanged
    if (evt.getStateChange()==ItemEvent.SELECTED){
        try{
              com.mysql.jdbc.PreparedStatement pr = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            Connection con =  (Connection) conn.getConexion();
            com.mysql.jdbc.PreparedStatement pw = null;
            ResultSet rw = null;   
            pw =(com.mysql.jdbc.PreparedStatement) con.prepareStatement("SELECT *FROM notas INNER JOIN alumno ON notas.Id_Alumno=alumno.Id_Alumno inner JOIN materia ON notas.Id_Materia=materia.Id_Materia INNER JOIN grado on notas.Id_Grado=grado.Id_Grado WHERE alumno.NombreAlumno='"+txt_nombre.getText()+"' and alumno.ApellidoAlumno='"+txt_apellido.getText()+"' AND materia.Materia='"+cbx_materia.getSelectedItem()+"' AND grado='"+txt_grado.getText()+"'");
           
            rw = pw.executeQuery();

            if(rw.next())
            {
                JOptionPane.showMessageDialog(null,"Datos de usuario encontrado");
                jPanel1.setVisible(true);
                txt_bimestre1.setEnabled(false);
               txt_bimestre2.setEnabled(false);
               txt_bimestre3.setEnabled(false);
               txt_bimestre4.setEnabled(false);
               txt_promedio.setEnabled(false);
               cbx_Bimestre.setEnabled(true);
               
               txt_nombre.setText(rw.getString("nombrealumno"));
               txt_apellido.setText(rw.getString("apellidoalumno"));
               txt_bimestre1.setText(Integer.toString(rw.getInt("nota_primer_bimestre")));
               txt_bimestre2.setText(Integer.toString(rw.getInt("nota_segundo_bimestre")));
               txt_bimestre3.setText(Integer.toString(rw.getInt("nota_tercer_bimestre")));
               txt_bimestre4.setText(Integer.toString(rw.getInt("nota_cuarto_bimestre")));
               txt_promedio.setText(Integer.toString(rw.getInt("promedio")));
               txt_año.setText(rw.getString("año"));
               cod_materia=rw.getInt("id_materia");
               cod_notas= rw.getInt("id_notas");
            }else{            
       txt_bimestre1.setText("0"); txt_bimestre2.setText("0"); txt_bimestre3.setText("0"); txt_bimestre4.setText("0"); txt_promedio.setText("0");
         try{
            com.mysql.jdbc.PreparedStatement pq = null;
            ResultSet rq = null;   
            pq =(com.mysql.jdbc.PreparedStatement) con.prepareStatement("SELECT * FROM materia where materia='"+cbx_materia.getSelectedItem()+"'");
           
            rq = pq.executeQuery();

            if(rq.next())
            {
                cod_materia=rq.getInt("Id_materia");
            }else{
                JOptionPane.showMessageDialog(null,"Error no se pudo encontrar datos de la tabla materia...");

            }

        }catch(Exception e){
            System.err.println("Error en la BD al buscar el id maeria");
            
        }
       
       try{ 
           
           
        pr = (com.mysql.jdbc.PreparedStatement) con.prepareStatement("INSERT INTO `notas` (`nota_primer_bimestre`, `nota_segundo_bimestre`, `nota_tercer_bimestre`, `nota_cuarto_bimestre`, `Promedio`, `Año`, `Id_Materia`, `Id_Alumno`, id_grado) VALUES (?,?,?,?,?,?,?,?,?)");
        pr.setInt(1,Integer.parseInt(txt_bimestre1.getText()));
        pr.setInt(2,Integer.parseInt(txt_bimestre2.getText()));
        pr.setInt(3,Integer.parseInt(txt_bimestre3.getText()));
        pr.setInt(4,Integer.parseInt(txt_bimestre4.getText()));
        pr.setInt(5,Integer.parseInt(txt_promedio.getText()));
        pr.setString(6,txt_año.getText());
        pr.setInt(7,cod_materia);
        pr.setInt(8,cod_Alumno);
        pr.setInt(9,cod_grado);
                int res = pr.executeUpdate();
            
            if(res > 0)
            {
                JOptionPane.showMessageDialog(null,"Se guardo un nuevo registro de notas");
                cbx_Bimestre.setEnabled(true);
                btn_guardar.setEnabled(true);
                 NotasOpciones menu = new NotasOpciones();
        menu.setVisible(true);
        this.setVisible(false);
                
            }else{
                JOptionPane.showMessageDialog(null," Error no se pudo guardar nuevo registro de notas...");
                
            } 
        con.close();
    }catch(Exception e){
        System.err.println(" Error en la BD al insertar nuevo registro de notas");
    }

       
            }

        }catch(Exception e){
            System.err.println("Error en la BD registro de notas");
            
        }
        }
    }//GEN-LAST:event_cbx_materiaItemStateChanged

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
               
        String nombre, apellido, año;
        nombre=txt_nombre.toString();
        apellido=txt_apellido.toString();
        año=txt_año.toString();
        try {
            // TODO add your handling code here:
            Conexion con = new Conexion();
            java.sql.Connection conn = con.getConexion();
            JasperReport reporte = null;
            String patch ="src\\vista\\NotasAlumno.jasper";
            reporte =(JasperReport) JRLoader.loadObjectFromFile(patch);
             Map parametroP = new HashMap();
            parametroP.put("nombre",nombre);
            parametroP.put("apellido",apellido);
            parametroP.put("año",año);
            JasperPrint jprint = JasperFillManager.fillReport(reporte,parametroP,conn);
            JasperViewer view = new JasperViewer(jprint,false);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
            
        } catch (JRException ex) {
            Logger.getLogger(Notas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JComboBox<String> cbx_Bimestre;
    private javax.swing.JComboBox<String> cbx_materia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private LIB.JPanelTransparente jPanelTransparente1;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_año;
    private javax.swing.JTextField txt_bimestre1;
    private javax.swing.JTextField txt_bimestre2;
    private javax.swing.JTextField txt_bimestre3;
    private javax.swing.JTextField txt_bimestre4;
    private javax.swing.JTextField txt_grado;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_promedio;
    // End of variables declaration//GEN-END:variables
}
