/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Objetos.Conexion;
import Objetos.Documentos;
import Objetos.Grados;
import Objetos.Jornada;
import Objetos.Secciones;
import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author asd
 */
public class Nuevo_alumno extends javax.swing.JFrame {

    /**
     * Creates new form Nuevo_alumno1
     */
    public Nuevo_alumno() {
        initComponents();
       
         this.setLocationRelativeTo(null);
        this.setResizable(false);
        Documentos Doc = new Documentos();
           DefaultComboBoxModel modeloDocumentos = new DefaultComboBoxModel(Doc.mostrarDocumentos());
           cbx_DocumentoAlumno.setModel(modeloDocumentos);
           
           Grados Cg = new Grados();
           DefaultComboBoxModel modeloGrado = new DefaultComboBoxModel(Cg.mostrarGrados());
           cbx_Grado.setModel(modeloGrado);
           
           Secciones Sc = new Secciones();
           DefaultComboBoxModel modeloSeccion = new DefaultComboBoxModel(Sc.mostrarSecciones());
           cbx_Seccion.setModel(modeloSeccion);
           
           Jornada Jd = new Jornada();
           DefaultComboBoxModel modeloJornada = new DefaultComboBoxModel(Jd.mostrarJornada());
           cbx_Jornada.setModel(modeloJornada);
           
           Calendar cal= Calendar.getInstance();
           txt_Año.setText(Integer.toString(cal.get(Calendar.YEAR)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panel_fondo1 = new javax.swing.JPanel();
        nuevoalumno1 = new javax.swing.JLabel();
        jPanelRound2 = new LIB.JPanelRound();
        numero2 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        panel_2 = new javax.swing.JPanel();
        primer_nombre1 = new javax.swing.JLabel();
        Primer_apellido1 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        txt_Apellido = new javax.swing.JTextField();
        obligatorio13 = new javax.swing.JLabel();
        obligatorio14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        calendario_fecha_alumno = new com.toedter.calendar.JDateChooser();
        obligatorio18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_CodigoPersonal = new javax.swing.JTextField();
        obligatorio15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        obligatorio19 = new javax.swing.JLabel();
        cbx_DocumentoAlumno = new javax.swing.JComboBox<>();
        txt_NoDocIdentificacion = new javax.swing.JTextField();
        obligatorio17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        obligatorio16 = new javax.swing.JLabel();
        txt_Nacionalidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        numero3 = new javax.swing.JLabel();
        titulo3 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbx_Grado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbx_Seccion = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbx_Jornada = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        nuevoalumno2 = new javax.swing.JLabel();
        txt_Año = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(742, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(720, 910));

        panel_fondo1.setBackground(new java.awt.Color(0, 120, 215));
        panel_fondo1.setMinimumSize(new java.awt.Dimension(730, 910));
        panel_fondo1.setPreferredSize(new java.awt.Dimension(740, 910));
        panel_fondo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nuevoalumno1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        nuevoalumno1.setText("Nuevo Alumno");
        panel_fondo1.add(nuevoalumno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 55));

        jPanelRound2.setBackground(new java.awt.Color(58, 58, 58));
        jPanelRound2.setOpaque(true);
        jPanelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numero2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/numero1.png"))); // NOI18N
        jPanelRound2.add(numero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        titulo2.setBackground(new java.awt.Color(180, 227, 255));
        titulo2.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        titulo2.setForeground(new java.awt.Color(35, 148, 128));
        titulo2.setText("Ingrese los datos personales");
        jPanelRound2.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        panel_2.setBackground(new java.awt.Color(0, 120, 215));
        panel_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        primer_nombre1.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        primer_nombre1.setText("Nombre");
        panel_2.add(primer_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 14, -1, -1));

        Primer_apellido1.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        Primer_apellido1.setText("Apellido");
        panel_2.add(Primer_apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txt_Nombre.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        txt_Nombre.setToolTipText("");
        txt_Nombre.setPreferredSize(new java.awt.Dimension(4, 38));
        txt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NombreActionPerformed(evt);
            }
        });
        panel_2.add(txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 10, 340, -1));

        txt_Apellido.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        txt_Apellido.setPreferredSize(new java.awt.Dimension(4, 38));
        panel_2.add(txt_Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 340, -1));

        obligatorio13.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        obligatorio13.setForeground(new java.awt.Color(241, 11, 0));
        obligatorio13.setText("*");
        panel_2.add(obligatorio13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        obligatorio14.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        obligatorio14.setForeground(new java.awt.Color(241, 11, 0));
        obligatorio14.setText("*");
        panel_2.add(obligatorio14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel1.setText("Fecha de Nacimiento");
        panel_2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        panel_2.add(calendario_fecha_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 243, 30));

        obligatorio18.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        obligatorio18.setForeground(new java.awt.Color(241, 11, 0));
        obligatorio18.setText("*");
        panel_2.add(obligatorio18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel3.setText("Codigo Personal");
        panel_2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        txt_CodigoPersonal.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        txt_CodigoPersonal.setPreferredSize(new java.awt.Dimension(4, 38));
        txt_CodigoPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CodigoPersonalActionPerformed(evt);
            }
        });
        panel_2.add(txt_CodigoPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 243, 34));

        obligatorio15.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        obligatorio15.setForeground(new java.awt.Color(241, 11, 0));
        obligatorio15.setText("*");
        panel_2.add(obligatorio15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Documento de Identificacion");
        panel_2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        obligatorio19.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        obligatorio19.setForeground(new java.awt.Color(241, 11, 0));
        obligatorio19.setText("*");
        panel_2.add(obligatorio19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        panel_2.add(cbx_DocumentoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 243, 34));

        txt_NoDocIdentificacion.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        txt_NoDocIdentificacion.setPreferredSize(new java.awt.Dimension(4, 38));
        panel_2.add(txt_NoDocIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 243, -1));

        obligatorio17.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        obligatorio17.setForeground(new java.awt.Color(241, 11, 0));
        obligatorio17.setText("*");
        panel_2.add(obligatorio17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Cod. documento identificacion");
        panel_2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        obligatorio16.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        obligatorio16.setForeground(new java.awt.Color(241, 11, 0));
        obligatorio16.setText("*");
        panel_2.add(obligatorio16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        txt_Nacionalidad.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        txt_Nacionalidad.setPreferredSize(new java.awt.Dimension(4, 38));
        panel_2.add(txt_Nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 240, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel8.setText("Nacionalidad");
        panel_2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jPanelRound2.add(panel_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 660, 350));

        numero3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/numero2.png"))); // NOI18N
        jPanelRound2.add(numero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        titulo3.setBackground(new java.awt.Color(180, 227, 255));
        titulo3.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        titulo3.setForeground(new java.awt.Color(35, 148, 128));
        titulo3.setText("Asignacion ");
        jPanelRound2.add(titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, -1, -1));

        panel2.setBackground(new java.awt.Color(0, 120, 215));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel7.setText("Nacionalidad");
        panel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel6.setText("Seccion");
        panel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 100, -1));

        panel2.add(cbx_Grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 180, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel9.setText("Jornada");
        panel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, -1));

        panel2.add(cbx_Seccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 70, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel10.setText("Grado ");
        panel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 90, -1));

        panel2.add(cbx_Jornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 120, 30));

        jPanelRound2.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 660, 190));

        jButton1.setBackground(new java.awt.Color(0, 120, 215));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerifyInputWhenFocusTarget(false);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelRound2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 750, 140, 110));

        btn_regresar.setBackground(new java.awt.Color(0, 120, 215));
        btn_regresar.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        btn_regresar.setText("Regresar");
        btn_regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_regresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_regresar.setVerifyInputWhenFocusTarget(false);
        btn_regresar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_regresar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        jPanelRound2.add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 750, -1, 110));

        panel_fondo1.add(jPanelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 700, 870));

        nuevoalumno2.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        nuevoalumno2.setText("Año");
        panel_fondo1.add(nuevoalumno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 40));
        panel_fondo1.add(txt_Año, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 110, -1));

        jScrollPane1.setViewportView(panel_fondo1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 740, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
        Menu_opciones menu = new Menu_opciones();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void txt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombreActionPerformed

    private void txt_CodigoPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CodigoPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CodigoPersonalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int año = calendario_fecha_alumno.getCalendar().get(Calendar.YEAR);
        int mes = calendario_fecha_alumno.getCalendar().get(Calendar.MARCH);
        int dia = calendario_fecha_alumno.getCalendar().get(Calendar.DAY_OF_MONTH);
        int cod_alumno=0;
        
String fecha =(año+"-"+mes+"-"+dia);
         try{
   com.mysql.jdbc.PreparedStatement pr = null;
    ResultSet rs = null;
   Conexion conn = new Conexion();
   Connection con =  (Connection) conn.getConexion();
  
        pr = (com.mysql.jdbc.PreparedStatement) con.prepareStatement("INSERT INTO alumno (`NombreAlumno`, `ApellidoAlumno`, `FechaNacimiento`, `CodigoIdentificacion`, `Nacionalidad`, `NoDocumentoIdentificacion`, `id_DocumentoIdentificacion`) VALUES (?,?,?,?,?,?,?)");
        pr.setString(1,txt_Nombre.getText());
        pr.setString(2,txt_Apellido.getText());
        pr.setString(3,fecha);
        pr.setString(4,txt_CodigoPersonal.getText());
        pr.setString(5,txt_Nacionalidad.getText());
        pr.setString(6,txt_NoDocIdentificacion.getText());
        pr.setInt(7,cbx_DocumentoAlumno.getSelectedIndex());

                int res = pr.executeUpdate();
            
            if(res > 0)
            {
                JOptionPane.showMessageDialog(null,"Alumno Guardado");
                                try{
            com.mysql.jdbc.PreparedStatement pw = null;
            ResultSet rw = null;   
            pw =(com.mysql.jdbc.PreparedStatement) con.prepareStatement("SELECT * FROM alumno where NombreAlumno='"+txt_Nombre.getText()+"'and ApellidoAlumno='"+txt_Apellido.getText()+"'");
           
            rw = pw.executeQuery();

            if(rw.next())
            {
                cod_alumno=rw.getInt("Id_Alumno");
            }else{
                JOptionPane.showMessageDialog(null,"Error no se pudo encontrar datos ...");

            }

        }catch(Exception e){
            System.err.println("Error en la BD");
            
        }
            }else{
                JOptionPane.showMessageDialog(null," Error no se pudo guardar datos ...");
            } 
        con.close();
    }catch(Exception e){
        System.err.println(" Error en la BD");
    }
 /* -------------------------------------------------------------------------------------------------------*/       
       try{
   com.mysql.jdbc.PreparedStatement pr = null;
    ResultSet rs = null;
   Conexion conn = new Conexion();
   Connection con =  (Connection) conn.getConexion();
  
        pr = (com.mysql.jdbc.PreparedStatement) con.prepareStatement("INSERT INTO `asignacion` ( `AñoAsignacion`, `Id_Alumno`, `Id_Seccion`, `Id_Grado`, `Id_Jornada`) VALUES (?,?,?,?,?)");
        pr.setString(1,txt_Año.getText());
        pr.setInt(2,cod_alumno);
        pr.setInt(3,cbx_Seccion.getSelectedIndex());
        pr.setInt(4,cbx_Grado.getSelectedIndex());
        pr.setInt(5,cbx_Jornada.getSelectedIndex());
        

                int res = pr.executeUpdate();
            
            if(res > 0)
            {
                JOptionPane.showMessageDialog(null,"Alumno Guardado");
            }else{
                JOptionPane.showMessageDialog(null," Error no se pudo guardar datos ...");
            } 
        con.close();
    }catch(Exception e){
        System.err.println(" Error en la BD");
    }
         
         
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuevo_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuevo_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuevo_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuevo_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nuevo_alumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Primer_apellido1;
    private javax.swing.JButton btn_regresar;
    private com.toedter.calendar.JDateChooser calendario_fecha_alumno;
    private javax.swing.JComboBox<String> cbx_DocumentoAlumno;
    private javax.swing.JComboBox<String> cbx_Grado;
    private javax.swing.JComboBox<String> cbx_Jornada;
    private javax.swing.JComboBox<String> cbx_Seccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private LIB.JPanelRound jPanelRound2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nuevoalumno1;
    private javax.swing.JLabel nuevoalumno2;
    private javax.swing.JLabel numero2;
    private javax.swing.JLabel numero3;
    private javax.swing.JLabel obligatorio13;
    private javax.swing.JLabel obligatorio14;
    private javax.swing.JLabel obligatorio15;
    private javax.swing.JLabel obligatorio16;
    private javax.swing.JLabel obligatorio17;
    private javax.swing.JLabel obligatorio18;
    private javax.swing.JLabel obligatorio19;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel_2;
    private javax.swing.JPanel panel_fondo1;
    private javax.swing.JLabel primer_nombre1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    private javax.swing.JTextField txt_Apellido;
    private javax.swing.JTextField txt_Año;
    private javax.swing.JTextField txt_CodigoPersonal;
    private javax.swing.JTextField txt_Nacionalidad;
    private javax.swing.JTextField txt_NoDocIdentificacion;
    private javax.swing.JTextField txt_Nombre;
    // End of variables declaration//GEN-END:variables
}
