/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author asd
 */
public class Opciones_Materia extends javax.swing.JFrame {

    /**
     * Creates new form Opciones_Materia
     */
    public Opciones_Materia() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_fondo = new LIB.JPanelRound();
        lbl_escoja_opcion = new javax.swing.JLabel();
        btn_menu_materia = new javax.swing.JButton();
        btn_pensum = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();

        setUndecorated(true);

        panel_fondo.setColorPrimario(new java.awt.Color(0, 120, 215));

        lbl_escoja_opcion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_escoja_opcion.setText("Escoga una opción");

        btn_menu_materia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_menu_materia.setText("Menu Materia");
        btn_menu_materia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu_materia.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btn_menu_materia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_menu_materia.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_menu_materia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_menu_materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_materiaActionPerformed(evt);
            }
        });

        btn_pensum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_pensum.setText("Pensum");
        btn_pensum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pensum.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btn_pensum.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pensum.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_pensum.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_pensum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pensumActionPerformed(evt);
            }
        });

        btn_regresar.setBackground(new java.awt.Color(0, 120, 215));
        btn_regresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logout.png"))); // NOI18N
        btn_regresar.setText("Regresar");
        btn_regresar.setBorder(null);
        btn_regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_regresar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btn_regresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_regresar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_regresar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_fondoLayout = new javax.swing.GroupLayout(panel_fondo);
        panel_fondo.setLayout(panel_fondoLayout);
        panel_fondoLayout.setHorizontalGroup(
            panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fondoLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(btn_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fondoLayout.createSequentialGroup()
                .addGap(0, 104, Short.MAX_VALUE)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_pensum, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_menu_materia, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_fondoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lbl_escoja_opcion)))
                .addGap(105, 105, 105))
        );
        panel_fondoLayout.setVerticalGroup(
            panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fondoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbl_escoja_opcion)
                .addGap(18, 18, 18)
                .addComponent(btn_menu_materia, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_pensum, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btn_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        Menu_opciones m=new Menu_opciones();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void btn_menu_materiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_materiaActionPerformed
        Materia ma=new Materia();
        ma.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_menu_materiaActionPerformed

    private void btn_pensumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pensumActionPerformed
       PensumVista p=new PensumVista();
       p.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btn_pensumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opciones_Materia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opciones_Materia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opciones_Materia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opciones_Materia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opciones_Materia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_menu_materia;
    private javax.swing.JButton btn_pensum;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JLabel lbl_escoja_opcion;
    private LIB.JPanelRound panel_fondo;
    // End of variables declaration//GEN-END:variables
}
