/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Objetos.Conexion;
import Objetos.Grados;
import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author asd
 */
public class Pensum extends javax.swing.JFrame {

    /**
     * Creates new form Pensum
     */
    DefaultListModel modeloGrad; String materia;
    public Pensum() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
           Grados Cg = new Grados();
           DefaultComboBoxModel modeloGrado = new DefaultComboBoxModel(Cg.mostrarGrados());
           cbx_grado.setModel(modeloGrado);
            modeloGrad = new DefaultListModel();
           list_materias.setModel(modeloGrad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_fondo = new LIB.JPanelRound();
        lbl_grado = new javax.swing.JLabel();
        lbl_año = new javax.swing.JLabel();
        lbl_listado = new javax.swing.JLabel();
        panel_corredizo = new javax.swing.JScrollPane();
        list_materias = new javax.swing.JList<>();
        cbx_grado = new javax.swing.JComboBox<>();
        txt_año = new javax.swing.JTextField();
        btn_generar_datos = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel_fondo.setColorPrimario(new java.awt.Color(0, 120, 215));
        panel_fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_grado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_grado.setText("Grado");
        panel_fondo.add(lbl_grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        lbl_año.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_año.setText("Año");
        panel_fondo.add(lbl_año, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        lbl_listado.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_listado.setText("Listado de Materias");
        panel_fondo.add(lbl_listado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        panel_corredizo.setViewportView(list_materias);

        panel_fondo.add(panel_corredizo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 90, 160));

        cbx_grado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_gradoActionPerformed(evt);
            }
        });
        panel_fondo.add(cbx_grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 100, 20));
        panel_fondo.add(txt_año, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 100, 20));

        btn_generar_datos.setBackground(new java.awt.Color(0, 120, 215));
        btn_generar_datos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_generar_datos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/analysis.png"))); // NOI18N
        btn_generar_datos.setText("Generar Datos");
        btn_generar_datos.setBorder(null);
        btn_generar_datos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_generar_datos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_generar_datos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_generar_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generar_datosActionPerformed(evt);
            }
        });
        panel_fondo.add(btn_generar_datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, 60));

        btn_regresar.setBackground(new java.awt.Color(0, 120, 215));
        btn_regresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logout.png"))); // NOI18N
        btn_regresar.setText("Regresar");
        btn_regresar.setBorder(null);
        btn_regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_regresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_regresar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_regresar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        panel_fondo.add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 120, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int i=0;
    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
         Menu_opciones m = new Menu_opciones();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void cbx_gradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_gradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_gradoActionPerformed

    private void btn_generar_datosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generar_datosActionPerformed
  
 /* try{
              com.mysql.jdbc.PreparedStatement pr = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            Connection con =  (Connection) conn.getConexion();
            com.mysql.jdbc.PreparedStatement pw = null;
            ResultSet rw = null;   
            pw =(com.mysql.jdbc.PreparedStatement) con.prepareStatement("SELECT *FROM pensum INNER JOIN grado ON pensum.Id_Grado=grado.Id_Grado INNER JOIN materia on pensum.Id_Materia=materia.Id_Materia WHERE grado.Grado='"+cbx_grado.getSelectedItem().toString()+"'AND pensum.año='"+txt_año.getText()+"'");
         
            rw = pw.executeQuery();

            if(rw.next())
            {
                materia=rw.getString("materia");
                // modeloGrad.addElement(rw.getString("materia"));
               // modeloGrad.addElement(rw.getString("materia") );
                
                
         }else{
                JOptionPane.showMessageDialog(null,"Error no se pudo encontrar datos ...");

            }
   
        }catch(Exception e){
            System.err.println("Error en la BD");
            
        }   
            */ 
        modeloGrad.addElement("materia");
        
        
    }//GEN-LAST:event_btn_generar_datosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pensum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pensum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pensum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pensum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pensum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_generar_datos;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JComboBox<String> cbx_grado;
    private javax.swing.JLabel lbl_año;
    private javax.swing.JLabel lbl_grado;
    private javax.swing.JLabel lbl_listado;
    private javax.swing.JList<String> list_materias;
    private javax.swing.JScrollPane panel_corredizo;
    private LIB.JPanelRound panel_fondo;
    private javax.swing.JTextField txt_año;
    // End of variables declaration//GEN-END:variables
}
